Disable phpunit coverage argument in arc unit command
Summary:
ref T239054. PHPUnit 8 doesn't support code coverage for PHP 8, which will cause arc unit to fail.

We don't track PHP unit test coverage in CI anyway.

Test Plan:
with `php8.0-xdebug` installed

before the change

```
jchen@FLSA001106:~/code/freelancer/gaf (master)$ arc unit --trace test/Core/Sentry/SentryHandlerTest.php
 ARGV  /usr/local/bin/arc unit --trace test/Core/Sentry/SentryHandlerTest.php
 LOAD  Loading library from "/opt/flarc/src"...
 LOAD  Loading library from "/home/jchen/code/freelancer/gaf/support/flarc/src"...
>>> [1] (+0) <exec> $ php -f /opt/arcanist/scripts/arcanist.php -- unit --trace test/Core/Sentry/SentryHandlerTest.php
 ARGV  /opt/arcanist/scripts/arcanist.php unit --trace test/Core/Sentry/SentryHandlerTest.php
 LOAD  Loaded "arcanist" from "/opt/arcanist/src".
Config: Reading user configuration file "/home/jchen/.arcrc"...
Config: Did not find system configuration at "/etc/arcconfig".
Working Copy: Reading .arcconfig from "/home/jchen/code/freelancer/gaf/.arcconfig".
Working Copy: Path "/home/jchen/code/freelancer/gaf" is part of `git` working copy "/home/jchen/code/freelancer/gaf".
Working Copy: Project root is at "/home/jchen/code/freelancer/gaf".
Config: Did not find local configuration at "/home/jchen/code/freelancer/gaf/.git/arc/config".
Loading phutil library from 'flarc/src'...
Loading phutil library from '/home/jchen/code/freelancer/gaf/support/flarc/src'...
>>> [1] (+0) <exec> $ which /home/jchen/code/freelancer/gaf/vendor/bin/phpunit
<<< [1] (+2) <exec> 2,062 us
 Source Tests
>>> [2] (+3) <exec> $ /home/jchen/code/freelancer/gaf/vendor/bin/phpunit '--configuration=phpunit.xml' '-d display_errors=stderr' '--log-junit=/tmp/au51iimzp6gw0ow8/1512052-MteMYt' '--coverage-clover=/tmp/7wgo2oh5cnc44cg8/1512052-ndllxv' test/Core/Sentry/SentryHandlerTest.php
<<< [2] (+932) <exec> 929,033 us
[2021-04-29 01:08:18] EXCEPTION: (ValueError) DOMDocument::loadXML(): Argument #1 ($source) must not be empty at [<flarc>/unit/parser/FlarcJunitTestResultParser.php:173]
arcanist(head=master, ref.master=b2e715fc5a9c), flarc(head=master, ref.master=1905cfcb44cd), flarc-gaf()
  #0 DOMDocument::loadXML(string) called at [<flarc>/unit/parser/FlarcJunitTestResultParser.php:173]
  #1 FlarcJunitTestResultParser::parseCloverCoverage(string) called at [<flarc>/unit/parser/FlarcJunitTestResultParser.php:98]
  #2 FlarcJunitTestResultParser::parseTestResults(string, string) called at [<flarc>/unit/engine/FreelancerPhpunitTestEngine.php:347]
  #3 FreelancerPhpunitTestEngine::parseTestResults(string, TempFile, TempFile, string) called at [<flarc>/unit/engine/FreelancerPhpunitTestEngine.php:160]
  #4 FreelancerPhpunitTestEngine::run() called at [<flarc-gaf>/unit/engine/FreelancerGafTestEngine.php:30]
  #5 FreelancerGafTestEngine::run() called at [<arcanist>/src/workflow/ArcanistUnitWorkflow.php:170]
  #6 ArcanistUnitWorkflow::run() called at [<arcanist>/scripts/arcanist.php:419]
<<< [1] (+1,004) <exec> 1,004,239 us
jchen@FLSA001106:~/code/freelancer/gaf (master)$ /home/jchen/code/freelancer/gaf/vendor/bin/phpunit '--configuration=phpunit.xml' '-d display_errors=stderr' '--log-junit=/tmp/au51iimzp6gw0ow8/1512052-MteMYt' '--coverage-clover=/tmp/7wgo2oh5cnc44cg8/1512052-ndllxv' test/Core/Sentry/SentryHandlerTest.php
PHPUnit 8.5.13 by Sebastian Bergmann and contributors.

Error:         This version of PHPUnit does not support code coverage on PHP 8

..........                                                        10 / 10 (100%)

Time: 905 ms, Memory: 22.00 MB

OK (10 tests, 10 assertions)
```

after the change
```
jchen@FLSA001106:~/code/freelancer/gaf (master)$ arc unit --trace test/Core/Sentry/SentryHandlerTest.php
 ARGV  /usr/local/bin/arc unit --trace test/Core/Sentry/SentryHandlerTest.php
 LOAD  Loading library from "/opt/flarc/src"...
 LOAD  Loading library from "/home/jchen/code/freelancer/gaf/support/flarc/src"...
>>> [1] (+0) <exec> $ php -f /opt/arcanist/scripts/arcanist.php -- unit --trace test/Core/Sentry/SentryHandlerTest.php
 ARGV  /opt/arcanist/scripts/arcanist.php unit --trace test/Core/Sentry/SentryHandlerTest.php
 LOAD  Loaded "arcanist" from "/opt/arcanist/src".
Config: Reading user configuration file "/home/jchen/.arcrc"...
Config: Did not find system configuration at "/etc/arcconfig".
Working Copy: Reading .arcconfig from "/home/jchen/code/freelancer/gaf/.arcconfig".
Working Copy: Path "/home/jchen/code/freelancer/gaf" is part of `git` working copy "/home/jchen/code/freelancer/gaf".
Working Copy: Project root is at "/home/jchen/code/freelancer/gaf".
Config: Did not find local configuration at "/home/jchen/code/freelancer/gaf/.git/arc/config".
Loading phutil library from 'flarc/src'...
Loading phutil library from '/home/jchen/code/freelancer/gaf/support/flarc/src'...
>>> [1] (+0) <exec> $ which /home/jchen/code/freelancer/gaf/vendor/bin/phpunit
<<< [1] (+2) <exec> 2,094 us
 Source Tests
>>> [2] (+3) <exec> $ /home/jchen/code/freelancer/gaf/vendor/bin/phpunit '--configuration=phpunit.xml' '-d display_errors=stderr' '--log-junit=/tmp/5m6l2kj1mccgk40s/1512558-FViaaL' test/Core/Sentry/SentryHandlerTest.php
<<< [2] (+77) <exec> 73,886 us
..........

<<< [1] (+153) <exec> 153,733 us
```
```

Reviewers: O8 Phabricator, dwang, #developer_experience, probles

Reviewed By: O8 Phabricator, dwang, #developer_experience, probles

Subscribers: probles

Maniphest Tasks: T239054

Differential Revision: https://phabricator.tools.flnltd.com/D167256