Revert "Pass `--read-only` to `docker run`"
Summary: Ref T87915. Revert D126319. For some reason, this breaks at least some linters.

Test Plan:
```name="docker run --mount type=bind,source=/home/josh/workspace/freelancer/gaf,target=/home/josh/workspace/freelancer/gaf --read-only --rm --workdir=/home/josh/workspace/freelancer/gaf php vendor/bin/phpcs --report=xml --standard=support/phpcs/gaf.xml /home/josh/workspace/freelancer/gaf/test.php", counterexample

Warning: file_put_contents(): Filename cannot be empty in /home/josh/workspace/freelancer/gaf/vendor/squizlabs/php_codesniffer/src/Reporter.php on line 159

Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: file_put_contents(): Filename cannot be empty in /home/josh/workspace/freelancer/gaf/vendor/squizlabs/php_codesniffer/src/Reporter.php on line 302 in /home/josh/workspace/freelancer/gaf/vendor/squizlabs/php_codesniffer/src/Runner.php:569
Stack trace:
#0 [internal function]: PHP_CodeSniffer\Runner->handleErrors(2, 'file_put_conten...', '/home/josh/work...', 302, Array)
#1 /home/josh/workspace/freelancer/gaf/vendor/squizlabs/php_codesniffer/src/Reporter.php(302): file_put_contents('', '<file name="/ho...', 10)
#2 /home/josh/workspace/freelancer/gaf/vendor/squizlabs/php_codesniffer/src/Runner.php(618): PHP_CodeSniffer\Reporter->cacheFileReport(Object(PHP_CodeSniffer\Files\LocalFile), Object(PHP_CodeSniffer\Config))
#3 /home/josh/workspace/freelancer/gaf/vendor/squizlabs/php_codesniffer/src/Runner.php(401): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#4 /home/josh/workspace/freelancer/gaf/vendor/squizlabs/php_codesniffer/src/Ru in /home/josh/workspace/freelancer/gaf/vendor/squizlabs/php_codesniffer/src/Runner.php on line 569
```

```name="docker run --mount type=bind,source=/home/josh/workspace/freelancer/gaf,target=/home/josh/workspace/freelancer/gaf --rm --workdir=/home/josh/workspace/freelancer/gaf php vendor/bin/phpcs --report=xml --standard=support/phpcs/gaf.xml /home/josh/workspace/freelancer/gaf/test.php"
<?xml version="1.0" encoding="UTF-8"?>
<phpcs version="3.4.0">
<file name="/home/josh/workspace/freelancer/gaf/test.php" errors="1" warnings="0" fixable="1">
    <error line="3" column="1" source="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingReturnTypeHint" severity="5" fixable="1">Function f() does not have void return type hint.</error>
</file>
</phpcs>
```

Reviewers: tpham

Reviewed By: tpham

Maniphest Tasks: T87915

Differential Revision: https://phabricator.tools.flnltd.com/D126323