Arcanist merge queue revert
Summary:
ref
T223421

```
$ arc version
arcanist 4b3baca999a4a229433c891cf69c2c4e2d634b89 (16 Oct 2020)
```
Implemented merge queue revert functionality for Arcanist.

Test Plan:
=====Help messages
```name=arc mergequeue-revert --help
MERGEQUEUE-REVERT WORKFLOW

mergequeue-revert --reason="reason" [commits]

Reverts the input commit hash(es) in the GAF master branch.

      --reason reason
          The reason for the revert.
```

=====Workflow successful use case
```name=mergequeue-revert for an API commit hash
$ arc mergequeue-revert c394faaa9e779334ad06d5daccb9be06337c0313 --reason "Test revert dummy diff"
 Found commits on the API repository...
 SUBMIT  Submitting to merge queue revert...
Done submitting to mergequeue-revert job.
```
The mergequeue-revert job is called with correct parameters and succeeds:
https://ci.tools.flnltd.com/job/API/job/mergequeue-revert-dev/8/

```name=mergequeue-revert for a GAF commit hash
$ arc mergequeue-revert d97f5d3cb5dd807245960df4d2edcb692f5bde36 --reason="Equally Important"
 Found commits on the GAF repository...
 SUBMIT  Submitting to merge queue revert...
Done submitting to mergequeue-revert job.
```
The mergequeue-revert job is called with correct parameters and succeeds:
https://ci.tools.flnltd.com/job/GAF/job/mergequeue-revert/227/
```name=mergequeue-revert for two GAF commit hashes
$ arc mergequeue-revert d97f5d3cb5dd807245960df4d2edcb692f5bde36 628ed3a373b6f94e265205b46c512f09dc4c2c8d --reason="Testing reversion of more than one commit at a time"
 Found commits on the GAF repository...
 SUBMIT  Submitting to merge queue revert...
Done submitting to mergequeue-revert job.
```
The mergequeue-revert job is called with correct parameters. : https://ci.tools.flnltd.com/job/GAF/job/mergequeue-revert/226/parameters/
There are only errors because it is attempting to revert empty commits.

=====Workflow error/validity checks
```name=No commit hashes specified
$ arc mergequeue-revert --reason="reason"
EXCEPTION: (ArcanistUsageException) Please specify atleast one commit hash. at [<flarc>/workflow/ArcanistMergeQueueRevertWorkflow.php:100]

```

```name=Any of the input commit hashes are invalid
$ arc mergequeue-revert 123fakecommit321 my_commit_hash --reason="reason"
EXCEPTION: (ArcanistUsageException) One or more commit hashes are invalid! at [<flarc>/workflow/ArcanistMergeQueueRevertWorkflow.php:156]

```

```name=Not all input commit hashes are in the same repo
$ arc mergequeue-revert c394faaa9e779334ad06d5daccb9be06337c0313 d97f5d3cb5dd807245960df4d2edcb692f5bde36 --reason="Very Important"
   Found commits on the API repository...
EXCEPTION: (ArcanistUsageException) All commit hashes must be in the same repository! at [<flarc>/workflow/ArcanistMergeQueueRevertWorkflow.php:175]

```

Reviewers: O8 Phabricator, #developer_experience, dwang, probles, gnavarro

Reviewed By: O8 Phabricator, #developer_experience, dwang, probles, gnavarro

Subscribers: gnavarro

Maniphest Tasks: T223421

Differential Revision: https://phabricator.tools.flnltd.com/D160937